"""ope_registros

Revision ID: 4044afe6b615
Revises: ee7ac69827ed
Create Date: 2026-02-02 15:59:26.919833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4044afe6b615'
down_revision: Union[str, Sequence[str], None] = 'ee7ac69827ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ope_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('o_beta', sa.String(length=50), nullable=True),
    sa.Column('booking', sa.String(length=50), nullable=True),
    sa.Column('awb', sa.String(length=50), nullable=True),
    sa.Column('chofer_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('transportista_id', sa.Integer(), nullable=False),
    sa.Column('termografos', sa.String(length=200), nullable=True),
    sa.Column('ps_beta', sa.String(length=80), nullable=True),
    sa.Column('ps_aduana', sa.String(length=80), nullable=True),
    sa.Column('ps_operador', sa.String(length=80), nullable=True),
    sa.Column('senasa', sa.String(length=80), nullable=True),
    sa.Column('ps_linea', sa.String(length=80), nullable=True),
    sa.Column('senasa_ps_linea', sa.String(length=120), nullable=True),
    sa.Column('dam', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chofer_id'], ['cat_choferes.id'], ),
    sa.ForeignKeyConstraint(['transportista_id'], ['cat_transportistas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['cat_vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ope_registros')
    # ### end Alembic commands ###
