"""refs posicionamiento y dams

Revision ID: 55ff5ba37e8d
Revises: 8379a6396418
Create Date: 2026-02-03 10:48:08.883083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ff5ba37e8d'
down_revision: Union[str, Sequence[str], None] = '8379a6396418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_booking_dam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking', sa.String(length=30), nullable=False),
    sa.Column('dam', sa.String(length=40), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_booking_dam_booking'), 'ref_booking_dam', ['booking'], unique=True)
    op.create_table('ref_posicionamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking', sa.String(length=30), nullable=False),
    sa.Column('o_beta', sa.String(length=30), nullable=True),
    sa.Column('awb', sa.String(length=30), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_posicionamiento_booking'), 'ref_posicionamiento', ['booking'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_posicionamiento_booking'), table_name='ref_posicionamiento')
    op.drop_table('ref_posicionamiento')
    op.drop_index(op.f('ix_ref_booking_dam_booking'), table_name='ref_booking_dam')
    op.drop_table('ref_booking_dam')
    # ### end Alembic commands ###
