"""init catalogos y unicos

Revision ID: 7efd8aa3d8e6
Revises: 
Create Date: 2026-02-02 14:39:18.127939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efd8aa3d8e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('primer_nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=80), nullable=False),
    sa.Column('apellido_materno', sa.String(length=80), nullable=True),
    sa.Column('licencia', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_choferes_dni'), 'cat_choferes', ['dni'], unique=True)
    op.create_table('cat_transportistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_sap', sa.String(length=30), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('nombre_transportista', sa.String(length=200), nullable=False),
    sa.Column('partida_registral', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_transportistas_codigo_sap'), 'cat_transportistas', ['codigo_sap'], unique=True)
    op.create_index(op.f('ix_cat_transportistas_nombre_transportista'), 'cat_transportistas', ['nombre_transportista'], unique=False)
    op.create_index(op.f('ix_cat_transportistas_ruc'), 'cat_transportistas', ['ruc'], unique=True)
    op.create_table('cat_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa_tracto', sa.String(length=20), nullable=False),
    sa.Column('placa_carreta', sa.String(length=20), nullable=True),
    sa.Column('placas', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('cert_vehicular', sa.String(length=80), nullable=True),
    sa.Column('largo_tracto', sa.Integer(), nullable=True),
    sa.Column('ancho_tracto', sa.Integer(), nullable=True),
    sa.Column('alto_tracto', sa.Integer(), nullable=True),
    sa.Column('largo_carreta', sa.Integer(), nullable=True),
    sa.Column('ancho_carreta', sa.Integer(), nullable=True),
    sa.Column('alto_carreta', sa.Integer(), nullable=True),
    sa.Column('configuracion_vehicular', sa.String(length=20), nullable=True),
    sa.Column('peso_neto_carreta', sa.Integer(), nullable=True),
    sa.Column('peso_neto_tracto', sa.Integer(), nullable=True),
    sa.Column('peso_bruto_vehicular', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_vehiculos_placas'), 'cat_vehiculos', ['placas'], unique=True)
    op.create_table('his_unicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('usuario', sa.String(length=80), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor', name='uq_unicos_tipo_valor')
    )
    op.create_index(op.f('ix_his_unicos_tipo'), 'his_unicos', ['tipo'], unique=False)
    op.create_index(op.f('ix_his_unicos_valor'), 'his_unicos', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_his_unicos_valor'), table_name='his_unicos')
    op.drop_index(op.f('ix_his_unicos_tipo'), table_name='his_unicos')
    op.drop_table('his_unicos')
    op.drop_index(op.f('ix_cat_vehiculos_placas'), table_name='cat_vehiculos')
    op.drop_table('cat_vehiculos')
    op.drop_index(op.f('ix_cat_transportistas_ruc'), table_name='cat_transportistas')
    op.drop_index(op.f('ix_cat_transportistas_nombre_transportista'), table_name='cat_transportistas')
    op.drop_index(op.f('ix_cat_transportistas_codigo_sap'), table_name='cat_transportistas')
    op.drop_table('cat_transportistas')
    op.drop_index(op.f('ix_cat_choferes_dni'), table_name='cat_choferes')
    op.drop_table('cat_choferes')
    # ### end Alembic commands ###
