"""his_unicos vigencia

Revision ID: 8e61a80b2532
Revises: 4044afe6b615
Create Date: 2026-02-02 16:32:54.555122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e61a80b2532'
down_revision: Union[str, Sequence[str], None] = '4044afe6b615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('his_unicos', sa.Column('vigente', sa.Boolean(), nullable=False))
    op.add_column('his_unicos', sa.Column('liberado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('his_unicos', 'liberado_en')
    op.drop_column('his_unicos', 'vigente')
    # ### end Alembic commands ###
