"""vehiculos medidas en metros y pesos obligatorios

Revision ID: ee7ac69827ed
Revises: 7efd8aa3d8e6
Create Date: 2026-02-02 15:19:03.913377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7ac69827ed'
down_revision: Union[str, Sequence[str], None] = '7efd8aa3d8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cat_vehiculos', 'largo_tracto',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'ancho_tracto',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'alto_tracto',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'largo_carreta',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'ancho_carreta',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'alto_carreta',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('cat_vehiculos', 'configuracion_vehicular',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cat_vehiculos', 'peso_neto_carreta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cat_vehiculos', 'peso_neto_tracto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cat_vehiculos', 'peso_bruto_vehicular',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cat_vehiculos', 'peso_bruto_vehicular',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'peso_neto_tracto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'peso_neto_carreta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'configuracion_vehicular',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cat_vehiculos', 'alto_carreta',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'ancho_carreta',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'largo_carreta',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'alto_tracto',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'ancho_tracto',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cat_vehiculos', 'largo_tracto',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
